site_name: T12 Piazza Panic
theme:
  name: material
nav:
 - Home : 'index.md'
 - Resources : 'resources.md'
 - Method Selection and Planning : 'overview.md'
 - Requirements: 'requirements.md'
 - Architecture: 'architecture.md'

