site_name: T12 Piazza Panic
theme:
  name: material
nav:
 - Home : 'index.md'
 - Resources : 'resources.md'
 - Method selection and planning : 'overview.md'
 - Requirment: 'requirments.md'
 - Architecture: 'architecture.md'

