@startgantt T12_Project_Gantt_Chart 
printscale weekly
project starts the 9th of november 2021
[Website] lasts 13 weeks
[Risk assessment and mitigation  (Ben)] as [TASK3] lasts 1 weeks
[Method selection and planning 20 marks (Billy, Ollie)] as [TASK1] lasts 1 weeks
[Requirements (Billy, Ben, Ollie)] as [TASK2] lasts 14 days 
[TASK2] is coloured in blue
[Architecture ] as [TASK4] lasts 14 days
[TASK4] is coloured in blue
[Holiday] as [BREAK] lasts 4 weeks
[Implementation] lasts 4 weeks
[EXAMS & SCRUM_4] as [TASK6] lasts 7 days
[Finalise Implementation] as [TASK5] lasts 14 days
[Finalise Implementation] is coloured in blue
[Hand In] as [TASK7] lasts 1 day
[TASK7] is coloured in red
[SCRUM_1] lasts 1 day
[SCRUM_2] lasts 1 day
[SCRUM_3] lasts 1 day
[SCRUM_5] lasts 1 day
[SCRUM_5] starts on the 14th of january 2022
[SCRUM_6] lasts 1 day
[SCRUM_6] starts on the 21th of january 2022
[SCRUM_7] lasts 1 day
[SCRUM_7] starts on the 28th of january 2022
[TASK1] -> [TASK2]
[TASK1] -> [SCRUM_1]
[TASK2] -> [TASK4]
[TASK2] -> [SCRUM_2]
[TASK4] -> [Implementation]
[TASK4] -> [BREAK]
[TASK4] -> [SCRUM_3]
[BREAK] -> [TASK6]
[TASK6] -> [TASK5]
[TASK5] -> [TASK7]

@endgantt