@startgantt Architecture_Breakdown 
[Stereotypes] lasts 4 weeks
[Patterns] lasts 4 weeks
[Component Diagram] lasts 4 weeks
[Class diagrams] lasts 4 weeks
[Behavioural diagrams] lasts 4 weeks
@endgantt